development:
  adapter: postgresql
  database: redminer_development
  template: template0
  encoding: utf8
  username: k41n
  password:
  host: localhost

test:
  adapter: postgresql
  database: redminer_test
  template: template0
  encoding: utf8
  username: k41n
  password:
  host: localhost
