# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039ce270723f3b09df3a0f05e7bc382b9ef1f7c39957a6593e49314a046a11826eee88884722d65e7b8a7fba86d9c9179753cc5651461fa79974f7fb4545141f

test:
  secret_key_base: af64f55b41ad837229546061142ef79fe42d2fb5b57c0ee0de4b2b4824d241afe647f9924b80855d82906b433839b9df0b6fdca1eab631f8eb1128f78dcb6145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
